import {
  RiAccountCircleFill,
  RiApps2Fill,
  RiAppsFill,
  RiArchiveDrawerFill,
  RiArchiveFill,
  RiBankCardFill,
  RiBankFill,
  RiBarChart2Fill,
  RiBarChartGroupedFill,
  RiBarChartHorizontalFill,
  RiBook3Fill,
  RiBookletFill,
  RiBookmark3Fill,
  RiBriefcase4Fill,
  RiBubbleChartFill,
  RiBuilding2Fill,
  RiCalendar2Fill,
  RiCalendarTodoFill,
  RiCoinFill,
  RiCoupon3Fill,
  RiCustomerService2Fill,
  RiDashboardFill,
  RiDatabase2Fill,
  RiDiscussFill,
  RiDraftFill,
  RiEqualizerFill,
  RiExchangeDollarFill,
  RiExchangeDollarLine,
  RiExchangeFill,
  RiExchangeFundsFill,
  RiExchangeFundsLine,
  RiFile3Fill,
  RiFileCopy2Fill,
  RiFileList3Fill,
  RiFilePaper2Fill,
  RiFileTextFill,
  RiFindReplaceFill,
  RiFlagFill,
  RiFolderFill,
  RiFolderOpenFill,
  RiFunctionFill,
  RiFundsFill,
  RiGlobalFill,
  RiGridFill,
  RiHandCoinFill,
  RiHotelFill,
  RiLineChartFill,
  RiLock2Fill,
  RiMessage2Fill,
  RiMoneyDollarCircleFill,
  RiMoneyEuroCircleFill,
  RiMoneyPoundCircleFill,
  RiNotification3Fill,
  RiNumbersFill,
  RiPencilRuler2Fill,
  RiPenNibFill,
  RiPercentFill,
  RiPieChart2Fill,
  RiPriceTag2Fill,
  RiPsychotherapyFill,
  RiQuestionAnswerFill,
  RiQuestionFill,
  RiRefreshFill,
  RiSafe2Fill,
  RiSafeFill,
  RiScales3Fill,
  RiSecurePaymentFill,
  RiSettings5Fill,
  RiShieldCheckFill,
  RiShoppingCart2Fill,
  RiStackFill,
  RiTableFill,
  RiTeamFill,
  RiWallet3Fill,
} from "react-icons/ri";

export const ICON_MAP = {
  SCALE: RiScales3Fill,
  FUNCTION: RiFunctionFill,
  LOCK: RiLock2Fill,
  SETTING: RiSettings5Fill,
  DRAFT: RiDraftFill,
  FILE_COPY: RiFileCopy2Fill,
  FILE_TEXT: RiFileTextFill,
  FILE: RiFile3Fill,
  FILE_LIST: RiFileList3Fill,
  FOLDER_OPEN: RiFolderOpenFill,
  SECURE_PAYMENT: RiSecurePaymentFill,
  EXCHANGE_DOLLAR: RiExchangeDollarFill,
  EXCHANGE_FUNDS: RiExchangeFundsLine,
  MONEY_EURO: RiMoneyEuroCircleFill,
  MONEY_POUND: RiMoneyPoundCircleFill,
  MONEY_DOLLAR: RiMoneyDollarCircleFill,
  FUND: RiFundsFill,
  PERCENT: RiPercentFill,
  BUBBLE_CHART: RiBubbleChartFill,
  BOOKMARK: RiBookmark3Fill,
  BANK: RiBankFill,
  STACK: RiStackFill,
  LINE_CHART: RiLineChartFill,
  GLOBAL: RiGlobalFill,
  FLAG: RiFlagFill,
  BRIEFCASE: RiBriefcase4Fill,
  BAR_CHART: RiBarChart2Fill,
  DATABASE: RiDatabase2Fill,
  FIND_REPLACE: RiFindReplaceFill,
  NOTIFICATION_FILL: RiNotification3Fill,
  REFRESH_FILL: RiRefreshFill,
  PYSCHO: RiPsychotherapyFill,
  TEAM: RiTeamFill,
  ACCOUNT_CIRCLE: RiAccountCircleFill,
  MESSAGE_FILL: RiMessage2Fill,
  DISCUSS_FILL: RiDiscussFill,
  QUESTION: RiQuestionAnswerFill,
  CUSTOMER_SERVICE: RiCustomerService2Fill,
  EQUALIZER: RiEqualizerFill,
  HOTEL: RiHotelFill,
  BUILDING: RiBuilding2Fill,
  QUESTION_FILL: RiQuestionFill,
  EXCHANGE_FILL: RiExchangeFill,
  EXCHANGES_FUNDS: RiExchangeFundsFill,
  COIN_FILL: RiCoinFill,
  DOLLAR_LINE: RiExchangeDollarLine,
  HAND_COIN: RiHandCoinFill,
  BANK_CARD: RiBankCardFill,
  WALLET: RiWallet3Fill,
  SAFE_FILL: RiSafeFill,
  SAFE2_FILL: RiSafe2Fill,
  SHOPPING_CART: RiShoppingCart2Fill,
  PRICE: RiPriceTag2Fill,
  COUPON: RiCoupon3Fill,
  SHIELD: RiShieldCheckFill,
  FOLDER_FILL: RiFolderFill,
  ARCHIVE_FILL: RiArchiveFill,
  ARCHIVES_DRAWER: RiArchiveDrawerFill,
  BOOKLET: RiBookletFill,
  BOOK_FILL: RiBook3Fill,
  CALENDAR: RiCalendar2Fill,
  CALENDAR_TODO: RiCalendarTodoFill,
  FILE_PAPER: RiFilePaper2Fill,
  PENCIL_RULER: RiPencilRuler2Fill,
  PEN_NIB: RiPenNibFill,
  NUMBERS_FILL: RiNumbersFill,
  APPS2_FILL: RiApps2Fill,
  APPS_FILL: RiAppsFill,
  DASHBOARD: RiDashboardFill,
  GRID: RiGridFill,
  PIE_CHART: RiPieChart2Fill,
  BAR_GROUP: RiBarChartGroupedFill,
  BAR_HORIZONTAL: RiBarChartHorizontalFill,
  TABLE_FILL: RiTableFill,
};
